# Generated by Django 5.2.8 on 2026-10-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('gmail', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=150)),
            ],
        ),
    ]
